---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 600

- name: Install apt requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "locales"
    - "apache2"
    - "php5"
    - "php5-cli"
    - "php5-common"
    - "php5-gd"
    - "php5-json"
    - "php5-ldap"
    - "php5-mysql"
    - "php5-pgsql"
    - "libapache2-mod-php5"

- name: Delete index.html from default directory
  file:
    path: /var/www/html/index.html 
    state: absent

- name: Copy apache2 configuration
  copy:
    src: apache_config
    dest: /etc/apache2/sites-available/000-default.conf

